# Generated by Django 2.0.13 on 2019-04-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20190418_2322'),
        ('clients', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Дата начала бронирования')),
                ('check_out_date', models.DateField(verbose_name='Дата конца бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время бронирования')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to='clients.Client', verbose_name='Арендатор')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.Room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Бронирование номера',
                'verbose_name_plural': 'Бронирования номеров',
            },
        ),
    ]
