# Generated by Django 2.0.13 on 2019-04-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_roombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='clients.Client', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotel.Room', verbose_name='Номер'),
        ),
    ]
