# Generated by Django 2.0.13 on 2019-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20190420_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменен'),
        ),
    ]
