# Generated by Django 2.1.7 on 2019-03-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='rooms/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1000, verbose_name='Цена за ночь в рублях')),
                ('description', models.TextField(blank=True, verbose_name='Описание номера')),
                ('room_size', models.IntegerField(default=20, verbose_name='Размер комнаты в м2')),
                ('sleeps_number', models.IntegerField(default=2, verbose_name='Количество человек в одном номере')),
                ('room_status', models.CharField(choices=[('available', 'Доступный для проживания'), ('booked', 'Забронирован'), ('unavailable', 'Временно не доступен')], default='available', max_length=255, verbose_name='Статус номера')),
                ('check_in_date', models.DateField(blank=True, help_text='Дата с которой номер меняет статус на "забронирован"', null=True, verbose_name='Дата начала бронирования')),
                ('check_out_date', models.DateField(blank=True, help_text='Дата с которой номер меняет статус на "свободный"', null=True, verbose_name='Дата конца бронирования')),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='rooms/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Фонд номеров',
                'verbose_name_plural': 'Фонд номеров',
            },
        ),
        migrations.AddField(
            model_name='extrapictures',
            name='rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_pictures', to='hotel.Room'),
        ),
    ]
