# Generated by Django 2.1.7 on 2019-04-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Дополнительные услуги',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='extra_services',
            field=models.ManyToManyField(related_name='rooms', to='hotel.ExtraService', verbose_name='Дополнительные услуги'),
        ),
    ]
