# Generated by Django 2.1.7 on 2019-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
            ],
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Фонд номеров', 'verbose_name_plural': 'Фонд номеров'},
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='rooms',
            field=models.ManyToManyField(related_name='additionalServices', to='hotel.Room'),
        ),
    ]
