# Generated by Django 2.1.7 on 2019-03-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20190323_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalservice',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='additionalServices',
            field=models.ManyToManyField(related_name='rooms', to='hotel.AdditionalService'),
        ),
    ]
