# Generated by Django 2.1.7 on 2019-03-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20190323_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='additionalServices',
            field=models.ManyToManyField(related_name='rooms', to='hotel.AdditionalService', verbose_name='Дополнительные услуги'),
        ),
    ]
