# Generated by Django 2.0.13 on 2019-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20190413_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Доступный для проживания', 'Доступный для проживания'), ('Забронирован', 'Забронирован'), ('Временно недоступен', 'Временно не доступен')], default='Доступный для проживания', max_length=255, verbose_name='Статус номера'),
        ),
    ]
