# Generated by Django 2.1.7 on 2019-03-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20190327_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'verbose_name': 'Фонд дополнительных услуг', 'verbose_name_plural': 'Фонд дополнительных услуг'},
        ),
    ]
