# Generated by Django 2.0.13 on 2019-04-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название номера'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название услуги'),
        ),
    ]
