# Generated by Django 2.0.13 on 2019-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20190418_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_status',
        ),
        migrations.AddField(
            model_name='room',
            name='rooms_number',
            field=models.IntegerField(default=1, verbose_name='Количество однотипных номеров'),
        ),
        migrations.AlterField(
            model_name='room',
            name='extra_services',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hotel.ExtraService', verbose_name='Дополнительные услуги'),
        ),
    ]
